spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3309/eshop-backend-db
    username: user
    password: db#1234
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER



keycloak:
  auth-server-url: http://localhost:8281/auth
  realm: master
  client-id: eshop_backend
  client-secret: C4MHtNVAt2cd3upSOjJ6fen4xVUCrUwP
  use-resource-role-mappings: true


server:
  port: 8182
  error:
    include-message: always


springdoc:
  swagger-ui:
    path: /swagger*