spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/auth/realms/eshop_backend
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3309/eshop-backend-db
    username: user
    password: db#1234


keycloak:
  auth-server-url: http://localhost:8181/auth
  realm: eshop_backend
  client-id: eshop_backend
  client-secret: Z9TWYDnhz9RQVGxDKorlCWuCchv7c1rP
  use-resource-role-mappings: true




